%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Z:\Daten\MFVSZ\Wetterstation\Anemometer\Simulation\Magnet_5x2x2_distance.csv
%
% Auto-generated by MATLAB on 10-May-2020 08:56:28

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Distance", "FluxDensity"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Magnet5x2x2distance = readtable("Z:\Daten\MFVSZ\Wetterstation\Anemometer\Simulation\Magnet_5x2x2_distance.txt", opts);


%% Clear temporary variables
clear opts