/*
 * interval.c
 *
 *  Created on: 24.08.2021
 *      Author: daniw
 */

#include "interval.h"

#if PL_HAS_INTERVAL

/* Variables */

/* Functions */
void init_interval(void){
    /* Initialize registers */
    #if INTERVAL_R_INIT != INTERVAL_R_DEFAULT
        INTERVAL_R = INTERVAL_R_INIT;
    #endif
    #if INTERVAL_TBEX0_INIT != INTERVAL_EX0_DEFAULT
        INTERVAL_EX0 = INTERVAL_TBEX0_INIT;
    #endif
    #if INTERVAL_CCR0_INIT != INTERVAL_CCR_DEFAULT
        INTERVAL_CCR0 = INTERVAL_CCR0_INIT;
    #endif
    #if INTERVAL_CCR1_INIT != INTERVAL_CCR_DEFAULT
        INTERVAL_CCR1 = INTERVAL_CCR1_INIT;
    #endif
    #if INTERVAL_CCR2_INIT != INTERVAL_CCR_DEFAULT
        INTERVAL_CCR2 = INTERVAL_CCR2_INIT;
    #endif
    #if INTERVAL_CCR3_INIT != INTERVAL_CCR_DEFAULT
        INTERVAL_CCR3 = INTERVAL_CCR3_INIT;
    #endif
    #if INTERVAL_CCR4_INIT != INTERVAL_CCR_DEFAULT
        INTERVAL_CCR4 = INTERVAL_CCR4_INIT;
    #endif
    #if INTERVAL_CCR5_INIT != INTERVAL_CCR_DEFAULT
        INTERVAL_CCR5 = INTERVAL_CCR5_INIT;
    #endif
    #if INTERVAL_CCR6_INIT != INTERVAL_CCR_DEFAULT
        INTERVAL_CCR6 = INTERVAL_CCR6_INIT;
    #endif
    #if INTERVAL_CCTL0_INIT != INTERVAL_CCTL_DEFAULT
        INTERVAL_CCTL0 = INTERVAL_CCTL0_INIT;
    #endif
    #if INTERVAL_CCTL1_INIT != INTERVAL_CCTL_DEFAULT
        INTERVAL_CCTL1 = INTERVAL_CCTL1_INIT;
    #endif
    #if INTERVAL_CCTL2_INIT != INTERVAL_CCTL_DEFAULT
        INTERVAL_CCTL2 = INTERVAL_CCTL2_INIT;
    #endif
    #if INTERVAL_CCTL3_INIT != INTERVAL_CCTL_DEFAULT
        INTERVAL_CCTL3 = INTERVAL_CCTL3_INIT;
    #endif
    #if INTERVAL_CCTL4_INIT != INTERVAL_CCTL_DEFAULT
        INTERVAL_CCTL4 = INTERVAL_CCTL4_INIT;
    #endif
    #if INTERVAL_CCTL5_INIT != INTERVAL_CCTL_DEFAULT
        INTERVAL_CCTL5 = INTERVAL_CCTL5_INIT;
    #endif
    #if INTERVAL_CCTL6_INIT != INTERVAL_CCTL_DEFAULT
        INTERVAL_CCTL6 = INTERVAL_CCTL6_INIT;
    #endif
    #if INTERVAL_CTL_INIT != INTERVAL_CTL_DEFAULT
        INTERVAL_CTL = INTERVAL_CTL_INIT;
    #endif
    return;
}

void interval_isr(void){
}

#endif /* PL_HAS_INTERVAL */
